### ISSUE TITLE
在已经有代码的基础上，如何方便的拉取 getting-started 的更新？

### ISSUE THREAD

**Issue by nicecui** [leancloud/multiplayer-server-plugin-getting-started#1]
之前拉的老版本的 getting-started 仓库，在老仓库的基础上已经写了一些自己的自定义代码。如今要升级到新版本，发现新的 getting-started 和自定义代码有冲突，所以目前是这样做的：

1. 先把自己自定义的代码复制一份到别的地方
2. 删掉老的仓库代码
3. 重新下载一份新的 getting-started
4. 将自己复制的代码再重新放到新的 getting-started 里面

请问频繁改动 getting-started 的情况是暂时的，还是经常会有变动？如果经常有变动，能否有一个比较好的方式更新代码？
例如像 https://github.com/leancloud/client-engine-nodejs-getting-started 这个仓库一样，项目结构基本上没有变化，仅项目依赖的 client engine sdk 会有版本的升级。

**Comment by jysperm** [comment]
按照云引擎其他 getting-started 的情况，一般用户从 getting-started 复制代码之后就不需要更新了，因为 getting-started 起到的是一个示例的作用，其中真正有用的代码很少（这些应该放到 SDK，也就是 multiplayer-server-plugin 里）

当然现在在开发阶段可能确实 getting-started 变动比较频繁。

**Comment by jysperm** [comment]
或者如果你想要更新的话，可以 clone getting-started 的完整 git 历史，有了自己的修改之后，在  getting-started 有更新的时候 git rebase origin/master

**Comment by nicecui** [comment]
开发阶段确实变动会比较频繁，预期是上线后会尽可能稳定下来。
git rebase 感觉比较复杂，我先按照复制粘贴的方式来合并代码吧。

**Comment by ylgrgyq** [comment]
> 按照云引擎其他 getting-started 的情况，一般用户从 getting-started 复制代码之后就不需要更新了，因为 getting-started 起到的是一个示例的作用，其中真正有用的代码很少（这些应该放到 SDK，也就是 multiplayer-server-plugin 里）

我也是认为这个工程只是示例，用户拷贝走修改后就不会再跟这个工程绑定了。
我理解这里目前并没有问题，所以先关闭了？
